//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdivinaQue.Host.DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int IdPlayer { get; set; }
        public int totalGames { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
